[patch_servers]
ubuntu24 ansible_host=localhost ansible_port=2222 ansible_user=kanimozhi

[patch_servers:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
