---
- name: Generic Package Update
  hosts: "{{ HOSTS }}"
  become: yes
  gather_facts: yes

  tasks:

    - name: Update package to latest
      package:
        name: "{{ PACKAGE }}"
        state: latest
      when: VERSION == "" or VERSION == "latest"

    - name: Install specific version (Debian)
      apt:
        name: "{{ PACKAGE }}={{ VERSION }}"
        state: present
        allow_downgrade: yes
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - VERSION != ""
        - VERSION != "latest"

    - name: Install specific version (RedHat)
      package:
        name: "{{ PACKAGE }}-{{ VERSION }}"
        state: present
      when:
        - ansible_os_family == "RedHat"
        - VERSION != ""
        - VERSION != "latest"

    - name: Verify Installed Version
      package_facts:

    - debug:
        var: ansible_facts.packages[PACKAGE]
